### ISSUE TITLE
include network argument in every POST and GET ..

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/cytoscape-api#8]
if we could have the `network=` argument in every function it would be easy to have cytoscape running as a service where users use random keys to name their networks

PS. Amazing API, always wanted to have something like this around!

**Comment by AlexanderPico** [comment]
Intriguing idea. There may be a few other entities that require unique names, like style names.  I'm assigning David Otasek, because I suspect he's thought the most about this and may know of other obstacles... or confirm the possibility.

Thanks!

**Comment by dotasek** [comment]
Could I get a little more info on how you would expect this to work? A sample function call, with a url, path variables, and the expected result would be helpful.

As it stands now, CyREST refers to networks exclusively by SUID. You can find corresponding names via the /v1/networks.names endpoint.

**Comment by jorgeboucas** [comment]
got it! 

so if I want to make sure the users using the R library are not gonna start doing strange things in each others graphs I should probably fork the repo and transform all functions with `network='current'`

eg.
`mapVisualProperty <- function(visual.prop, table.column, mapping.type, table.column.values, 
                              visual.prop.values, network='current', base.url='http://localhost:1234/v1')`

into:
`mapVisualProperty <- function(network , visual.prop, table.column, mapping.type, table.column.values, 
                              visual.prop.values, base.url='http://localhost:1234/v1')`

Thanks!

**Comment by AlexanderPico** [comment]
Reopening... we were asking for examples and more details, not saying 'no'.  For example, I'm more than happy to add network params to all functions in r2cytoscape, where it works.  I'm sure I missed a couple, but you can't simply add the parameter to EVERY function and expect it to do something. Can you point to particular functions where it is missing?

The example you gave, doesn't make sense to me. The 'network' parameter is already there. It has a default value, but you can override that by specifying it as 'network=<unique id>'.  Replacing the current param with one without a default and positioned earlier, doesn't add any new functionality.

Further, note that David's comment about the use of SUID might actually be part of the solution to your proposal. The SUID is a random, unique ID per network already assigned per session. So this might already work for your proposed use case.

I suspect you won't have to change much to get this to work. So, that's why we're asking for more details, because perhaps we are missing something. This doesn't mean that we aren't willing to make changes.

**Comment by AlexanderPico** [comment]
Ok. Closing here. Will reopen as something to test out in the cytoscape-automation repo...
https://github.com/cytoscape/cytoscape-automation/issues/21
